#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/Calculator_MatrixJobExam/ && \
    dotnet build src/Calculator_MatrixJobExam/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Calculator_MatrixJobExam/Calculator_MatrixJobExam.csproj --launch-profile web"
