:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore Calculator_MatrixJobExam
dotnet build Calculator_MatrixJobExam
echo Now, run the following to start the project: dotnet run -p Calculator_MatrixJobExam\Calculator_MatrixJobExam.csproj --launch-profile web.
echo.
